// Weather/client/src/components/Landing.jsx
import axios from "axios";
import React, { useState, useEffect, useContext } from "react";
import { AppContext } from "../App";
import rainDrop from "../assets/waterdrop.svg";
import closeX from "../assets/close.svg";

const Landing = () => {
	const {
		weath,
		setWeath,
		checked,
		tempColor,
		setTempColor,
		uv,
		setUv,
		cityWeath,
		setCityWeath,
		uvColor,
		setUvColor,
	} = useContext(AppContext);
	const [loading, setLoading] = useState(true);
	const dayjs = require("dayjs");
	var advancedFormat = require("dayjs/plugin/advancedFormat");
	dayjs.extend(advancedFormat);
	const hideAlert = () => {
        document.getElementById("alert").style.display = "none";
	};
	useEffect(() => {
        const getWeather = async () => {
            const mostRecent = JSON.parse(localStorage.getItem("rc"))[0];
			const theWeather = await (checked
				? axios.get(
						`https://api.openweathermap.org/data/2.5/onecall?lat=${mostRecent.lat}&lon=${mostRecent.lon}&exclude=minutely&units=imperial&appid=9ce1a7cb8abfdaed2fdb4b805a138c09`
				  )
				: axios.get(
						`https://api.openweathermap.org/data/2.5/onecall?lat=${mostRecent.lat}&lon=${mostRecent.lon}&exclude=minutely&units=metric&appid=9ce1a7cb8abfdaed2fdb4b805a138c09`
				  ));
			const theCity = await axios.get(
				`http://api.openweathermap.org/geo/1.0/reverse?lat=${mostRecent.lat}&lon=${mostRecent.lon}&limit=5&appid=9ce1a7cb8abfdaed2fdb4b805a138c09`
			);
			setWeath(theWeather.data);
			setCityWeath(theCity.data[0]);
			if (theWeather.data.daily[0].uvi < 3) {
				setUv("Low");
				// setUvColor("#67BE4D");
			} else if (theWeather.data.daily[0].uvi < 6) {
				setUv("Moderate");
				// setUvColor("#FCBD22");
			} else if (theWeather.data.daily[0].uvi < 8) {
				setUv("High");
				// setUvColor("#F66B34");
			} else if (theWeather.data.daily[0].uvi > 7) {
				setUv("Very High") && setUvColor("#FF0000");
			}
			if (checked && theWeather.data.current.temp >= 90) {
				setTempColor("#d5202a");
			} else if (checked && theWeather.data.current.temp >= 75) {
				setTempColor("#ff8833");
			} else if (checked && theWeather.data.current.temp >= 60) {
				setTempColor("#ffb92f");
			} else if (checked && theWeather.data.current.temp >= 45) {
				setTempColor("#5b9f49");
			} else if (checked && theWeather.data.current.temp >= 30) {
				setTempColor("#15aadc");
			} else if (checked && theWeather.data.current.temp >= 15) {
				setTempColor("#0053ae");
			} else if (checked && theWeather.data.current.temp < 15) {
				setTempColor("#ac54a0");
			} else if (!checked && theWeather.data.current.temp >= 30) {
				setTempColor("#d5202a");
			} else if (!checked && theWeather.data.current.temp >= 25) {
				setTempColor("#ff8833");
			} else if (!checked && theWeather.data.current.temp >= 15) {
				setTempColor("#ffb92f");
			} else if (!checked && theWeather.data.current.temp >= 5) {
				setTempColor("#5b9f49");
			} else if (!checked && theWeather.data.current.temp >= 0) {
				setTempColor("#15aadc");
			} else if (!checked && theWeather.data.current.temp >= -10) {
				setTempColor("#0053ae");
			} else if (!checked && theWeather.data.current.temp < -10) {
				setTempColor("#ac54a0");
			}
			setLoading(false);
		};
		const emptyWeather = async () => {
			const theWeather = await (checked
				? axios.get(
						`https://api.openweathermap.org/data/2.5/onecall?lat=41.87&lon=-87.65&exclude=minutely&units=imperial&appid=9ce1a7cb8abfdaed2fdb4b805a138c09`
				  )
				: axios.get(
						`https://api.openweathermap.org/data/2.5/onecall?lat=41.87&lon=-87.65&exclude=minutely&units=metric&appid=9ce1a7cb8abfdaed2fdb4b805a138c09`
				  ));
			const theCity = await axios.get(
				`http://api.openweathermap.org/geo/1.0/reverse?lat=41.87&lon=-87.65&limit=5&appid=9ce1a7cb8abfdaed2fdb4b805a138c09`
			);
			setWeath(theWeather.data);
			setCityWeath(theCity.data[0]);
			if (theWeather.data.daily[0].uvi < 3) {
				setUv("Low");
			} else if (theWeather.data.daily[0].uvi < 6) {
				setUv("Moderate");
			} else if (theWeather.data.daily[0].uvi < 8) {
				setUv("High");
			} else if (theWeather.data.daily[0].uvi > 7) {
				setUv("Very High");
			}
			if (checked && theWeather.data.current.temp >= 90) {
				setTempColor("#d5202a");
			} else if (checked && theWeather.data.current.temp >= 75) {
				setTempColor("#ff8833");
			} else if (checked && theWeather.data.current.temp >= 60) {
				setTempColor("#ffb92f");
			} else if (checked && theWeather.data.current.temp >= 45) {
				setTempColor("#5b9f49");
			} else if (checked && theWeather.data.current.temp >= 30) {
				setTempColor("#15aadc");
			} else if (checked && theWeather.data.current.temp >= 15) {
				setTempColor("#0053ae");
			} else if (checked && theWeather.data.current.temp < 15) {
				setTempColor("#ac54a0");
			} else if (!checked && theWeather.data.current.temp >= 30) {
				setTempColor("#d5202a");
			} else if (!checked && theWeather.data.current.temp >= 25) {
				setTempColor("#ff8833");
			} else if (!checked && theWeather.data.current.temp >= 15) {
				setTempColor("#ffb92f");
			} else if (!checked && theWeather.data.current.temp >= 5) {
				setTempColor("#5b9f49");
			} else if (!checked && theWeather.data.current.temp >= 0) {
				setTempColor("#15aadc");
			} else if (!checked && theWeather.data.current.temp >= -10) {
				setTempColor("#0053ae");
			} else if (!checked && theWeather.data.current.temp < -10) {
				setTempColor("#ac54a0");
			}
			setLoading(false);
		};
		if (JSON.parse(localStorage.getItem("rc")) === null) {
			emptyWeather();
		} else {
			getWeather();
		}
	}, [checked]);
	return (
		<>
			{weath.alerts ? (
				<div id="alert">
					<div className="alertcontent">
						<p>
							{weath.alerts[0].tags} alert starting{" "}
							{dayjs(weath.alerts[0].start * 1000).format(
								"dddd MMMM Do h:mm A"
							)}{" "}
							until{" "}
							{dayjs(weath.alerts[0].end * 1000).format(
								"dddd MMMM Do h:mm A"
							)}
						</p>
						<img src={closeX} alt="" onClick={() => hideAlert()} />
					</div>
				</div>
			) : null}

			{loading === false ? (
				<div className="landing">
					<div className="landheader">
						<h1>{cityWeath.name}, {cityWeath.state}</h1>
					</div>

					<div className="content">
						<div className="current">
							<div className="currentheader">
								<h2>CURRENT</h2>
								<p>{weath.current.weather[0].main}</p>
							</div>
							<div className="currentinfo">
								<div className="icon">
									<img
										src={`http://openweathermap.org/img/wn/${weath.current.weather[0].icon}@4x.png`}
										alt=""
									/>
								</div>
								<div className="temp">
									<div className="tempnumber">
										<p>{weath.current.temp.toFixed()}</p>
										<p>{checked ? "°F" : "°C"}</p>
									</div>
									<p>
										Feels like{" "}
										{weath.current.feels_like.toFixed()}°
										{checked ? "F" : "C"}
									</p>
								</div>
							</div>
						</div>
						<div className="today">
							<h2>TODAY</h2>
							<p>
								{dayjs(weath.current.dt * 1000).format(
									"ddd M/D"
								)}
							</p>
							<p>{weath.daily[0].weather[0].description}</p>
							<p>
								High:&nbsp;
								{weath.daily[0].temp.max.toFixed()}
								{checked ? "°F" : "°C"}
							</p>
							<p>Humidity: {weath.daily[0].humidity}%</p>
							<div className="rain">
								<p>{weath.daily[0].pop}%</p>
								<img src={rainDrop} alt="" />
								{weath.daily[0].rain ? (
									<p>
										{(
											weath.daily[0].rain /
											10 /
											2.54
										).toFixed(2)}
										"
									</p>
								) : null}
							</div>
							<p>UV Index: {uv}</p>
						</div>
						<div className="tonight">
							<h2>TONIGHT</h2>
							<p>
								{dayjs(weath.current.dt * 1000).format(
									"ddd M/D"
								)}
							</p>
							<p>
								LOW
								<span
									style={{
										color: "#0d8af5",
										fontWeight: "bold",
									}}>
									{weath.daily[0].temp.min.toFixed()}
								</span>
								°{checked ? "F" : "C"}
							</p>
						</div>
					</div>
				</div>
			) : null}
		</>
	);
};

export default Landing;

// weather-angular/src/app/landing/landing.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DataService } from 'src/app/data.service';

@Component({
  selector: 'app-landing',
  templateUrl: './landing.component.html',
  styleUrls: ['./landing.component.scss'],
})
export class LandingComponent implements OnInit {
  cityList: any = JSON.parse(localStorage.getItem('rc') || '{}');
  weatherData: any;
  cityData: any;
  uv: any;

  constructor(private route: ActivatedRoute, public dataSerivce: DataService) {}

  ngOnInit(): void {
    console.log(this.cityList, "CITYLIST")
    if (Object.keys(this.cityList).length > 0) {
      this.dataSerivce
        .getData2(
          this.cityList[0].lat.toString(),
          this.cityList[0].lon.toString()
        )
        .subscribe((data) => {
          if (data) {
            this.weatherData = data;
          }
          if (this.weatherData.daily[0].uvi < 3) {
            this.uv = 'Low';
          } else if (this.weatherData.daily[0].uvi < 6) {
            this.uv = 'Moderate';
          } else if (this.weatherData.daily[0].uvi < 8) {
            this.uv = 'High';
          } else if (this.weatherData.daily[0].uvi > 7) {
            this.uv = 'Very High';
          } else {
            console.log(("HMMMMM"))
          }
        });
      this.dataSerivce
        .getCity(
          this.cityList[0].lat.toString(),
          this.cityList[0].lon.toString()
        )
        .subscribe((data) => {
          if (data) {
            this.cityData = data;
          }
        });
    } else {
      this.dataSerivce.getData().subscribe((data) => {
        if (data) {
          this.weatherData = data
          console.log(this.weatherData)
        } else {
          console.log("weather data problem")
        }
      });
      this.dataSerivce
        .getCity('41.8721', '-87.6578')
        .subscribe((data) => (this.cityData = data));
    }
  }
}

<div class="landing">
  <div class="landheader">
    <h1>{{ cityData[0].name }}, {{ cityData[0].state }}</h1>
  </div>
  <div class="content">
    <div class="current">
      <div class="currentheader">
        <h2>CURRENT</h2>
        <p>{{ weatherData.current.weather[0].description }}</p>
      </div>
      <div class="currentinfo">
        <div class="icon">
          <img
            src="http://openweathermap.org/img/wn/{{
              weatherData.current.weather[0].icon
            }}@4x.png"
            alt=""
          />
        </div>
        <div class="temp">
          <div class="tempnumber">
            <p>{{ weatherData.current.temp.toFixed() }}</p>
          </div>
          <p>
            Feels like
            {{ weatherData.current.feels_like.toFixed() }}°
          </p>
        </div>
      </div>
    </div>
    <div class="today">
      <h2>TODAY</h2>
      <p>
        {{ weatherData.dt * 1000 | date: "E L/d" }}
      </p>
      <p>{{ weatherData.daily[0].weather[0].description }}</p>
      <p>
        High:&nbsp;
        {{ weatherData.daily[0].temp.max.toFixed() }}
      </p>
      <p>Humidity: {{ weatherData.daily[0].humidity }}%</p>
      <div class="rain">
        <p>{{ weatherData.daily[0].pop * 100 }}%</p>
        <img src="../../assets/waterdrop.svg" alt="" />
        <p>
          {{
            weatherData.daily[0].rain
              ? (weatherData.daily[0].rain / 25.4).toFixed(2) + " inches"
              : null
          }}
        </p>
      </div>
      <p>UV Index: {{ uv }}</p>
    </div>
    <!-- <div class="tonight">
            <h2>TONIGHT</h2>
            <p>
                {dayjs(weath.current.dt * 1000).format(
                    "ddd M/D"
                )}
            </p>
            <p>
                LOW
                <span
                    style={{
                        color: "#0d8af5",
                        fontWeight: "bold",
                    }}>
                    {weath.daily[0].temp.min.toFixed()}
                </span>
                °{checked ? "F" : "C"}
            </p>
        </div> -->
  </div>
  <button>
    <a
      href="/weather/current/{{ cityData[0].name }}/{{ weatherData.lat }}/{{
        weatherData.lon
      }}"
      >Full Forecast</a
    >
  </button>
</div>
