// Weather/client/src/components/Forecast.jsx
import React from "react";
import { useContext } from "react";
import { AppContext } from "../App";
import rainDrop from "../assets/waterdrop.svg";

const Forecast = () => {
	const {
		checked,
		fcData,
	} = useContext(AppContext);
	const dayjs = require("dayjs");
	var advancedFormat = require("dayjs/plugin/advancedFormat");
	dayjs.extend(advancedFormat);
	return (
		<>
			<div className="header">
                <h2>8-Day Forecast</h2>
            </div>
			<div className="forecast">
				{fcData.map((day, index) => {
					return (
						<div className="daycast" key={index}>
							<h3>{dayjs(day.dt * 1000).format("ddd M/D")}</h3>
                            <div className="daycasttemps">
                                <p>{day.temp.max.toFixed()}°</p>&nbsp;|&nbsp;
                                <p>{day.temp.min.toFixed()}°</p>{checked ? "F" : "C"}
                            </div>
							<img
								src={`http://openweathermap.org/img/wn/${day.weather[0].icon}@4x.png`}
								alt=""
							/>
							<p>{day.weather[0].description}</p>
                            <div className="rain">
								<p>{(day.pop * 100).toFixed()}%</p>
								<img src={rainDrop} alt="" />
								{day.rain ? (
									<p>
										{(
											day.rain /
											25.4
										).toFixed(2)}
										"
									</p>
								) : null}
							</div>
						</div>
					);
				})}
			</div>
		</>
	);
};

export default Forecast;

// weather-angular/src/app/forecast/forecast.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DataService } from 'src/app/data.service';

@Component({
  selector: 'app-forecast',
  templateUrl: './forecast.component.html',
  styleUrls: ['./forecast.component.scss'],
})
export class ForecastComponent implements OnInit {
  city: any;
  lat: any;
  lon: any;
  weeklyData: any;

  constructor(private route: ActivatedRoute, public dataSerivce: DataService) {}

  ngOnInit(): void {
    this.city = this.route.snapshot.paramMap.get('city');
    this.lat = this.route.snapshot.paramMap.get('lat');
    this.lon = this.route.snapshot.paramMap.get('lon');
    this.dataSerivce
      .getForecast(this.lat, this.lon)
      .subscribe((data) => (this.weeklyData = data));
  }
}

<app-home></app-home>
<div class="wrapper">
  <div class="header">
    <h2>8-Day Forecast</h2>
  </div>
  <div class="forecast">
    <div *ngFor="let day of weeklyData.daily; index as i" class="daycast">
      <h3>{{ day.dt * 1000 | date: "E L/d" }}</h3>
      <div class="daycasttemps">
        <p>{{ day.temp.max.toFixed() }}°</p>
        &nbsp;|&nbsp;
        <p>{{ day.temp.min.toFixed() }}°</p>
      </div>
      <img
        src="http://openweathermap.org/img/wn/{{
          day.weather[0].icon
        }}@4x.png"
        alt=""
      />
      <p>{{ day.weather[0].description }}</p>
      <div class="rain">
        <p>{{ (day.pop * 100).toFixed() }}%</p>
        <img src="../../assets/waterdrop.svg" alt="" />
      </div>
    </div>
  </div>
</div>
