// weather-angular/src/app/hourly/hourly.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { DataService } from 'src/app/data.service';

@Component({
  selector: 'app-hourly',
  templateUrl: './hourly.component.html',
  styleUrls: ['./hourly.component.scss'],
})
export class HourlyComponent implements OnInit {
  city: any;
  lat: any;
  lon: any;
  hourData: any;

  constructor(private route: ActivatedRoute, public dataSerivce: DataService) {}

  ngOnInit(): void {
    this.city = this.route.snapshot.paramMap.get('city');
    this.lat = this.route.snapshot.paramMap.get('lat');
    this.lon = this.route.snapshot.paramMap.get('lon');
    this.dataSerivce
      .getHourData(this.lat, this.lon)
      .subscribe((data) => (this.hourData = data));
  }
}

<app-home></app-home>
<div class="header">
  <h2>Hourly Forecast</h2>
</div>
<div class="wrapper">
    <div class="hourly">
      <table>
        <thead class="rowgroup">
          <tr>
            <th>Time</th>
            <th>Conditions</th>
            <th>Temp</th>
            <th>Feels Like</th>
            <th>Precip</th>
            <th>Amount</th>
            <th>Cloud Cover</th>
            <th>Dew Point</th>
            <th>Humidity</th>
            <th>Wind</th>
          </tr>
        </thead>
        <tbody class="rowgroup">
          <tr *ngFor="let hour of hourData.hourly; index as i">
            <td>timestamp</td>
            <td class="desc">
              <img
                src="http://openweathermap.org/img/wn/{{
                  hour.weather[0].icon
                }}.png"
              />
              {{ hour.weather[0].description }}
            </td>
            <td>{{ hour.temp.toFixed() }}</td>
            <td>{{ hour.feels_like.toFixed() }}</td>
            <td>{{ (hour.pop * 100).toFixed() }} %</td>
            <td>
              {{  hour.rain ?
            (hour.rain["1h"] / 25.4).toFixed(2)
              + "in"  : "0 in" }}
            </td>
            <td>{{ hour.clouds }}%</td>
            <td>{{ hour.dew_point.toFixed() }}</td>
            <td>{{ hour.humidity }}%</td>
            <td>
              {{ hour.wind_speed.toFixed() }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
</div>

// Weather/client/src/components/Hourly.jsx
import React from "react";
import { useContext } from "react";
import { AppContext } from "../App";

const Hourly = () => {
	const {
		checked,
		hourData,
		moreLoad
	} = useContext(AppContext);
	const dayjs = require("dayjs");
	var advancedFormat = require("dayjs/plugin/advancedFormat");
	dayjs.extend(advancedFormat);
	return (
		<>
			<div className="hourly">
				<div className="header">
						<h2>
							Hourly Forecast
						</h2>
				</div>
				<table>
					<thead className="rowgroup">
						<tr>
							<th>Time</th>
							<th>Conditions</th>
							<th>Temp</th>
							<th>Feels Like</th>
							<th>Precip</th>
							<th>Amount</th>
							<th>Cloud Cover</th>
							<th>Dew Point</th>
							<th>Humidity</th>
							<th>Wind</th>
						</tr>
					</thead>
					<tbody className="rowgroup">
						{moreLoad
							? hourData.map((hour, index) => {
									return (
										<tr key={index}>
											<td>
												{dayjs(hour.dt * 1000).format(
													"h:mm A"
												)}
											</td>
											<td className="desc">
												<img
													src={`http://openweathermap.org/img/wn/${hour.weather[0].icon}.png`}
													alt=""
												/>
												{hour.weather[0].description}
											</td>
											<td>
												{hour.temp.toFixed()}
												{checked ? "°F" : "°C"}
											</td>
											<td>
												{hour.feels_like.toFixed()}
												{checked ? "°F" : "°C"}
											</td>
											<td>{hour.pop} %</td>
											{hour.rainy ? (
												<td>{hour.rain["1h"]} in</td>
											) : (
												<td>0 in</td>
											)}
											<td>{hour.clouds}%</td>
											<td>{hour.dew_point.toFixed()}{checked ? "°F" : "°C"}</td>
											<td>{hour.humidity}%</td>
											<td>
												{hour.wind_speed.toFixed()} {checked? "mph" : "km/h"}{" "}
											</td>
										</tr>
									);
							  })
							: null}
					</tbody>
				</table>
			</div>
		</>
	);
};

export default Hourly;
